#!/usr/bin/env bash
# =============================================================================
# 03b_fix_strand.sh — Fix strand/allele orientation issues in genotype data
# =============================================================================
# Corrects allele-orientation mismatches between the GWAS summary statistics
# and the genotype data, which show up as opposite-sign PGI distributions for
# a cohort × trait.
#
# This script:
#   1. Reads flip lists from diagnostic output (or uses default provided)
#   2. For each affected cohort × trait, uses PLINK2 --flip to correct alleles
#   3. Outputs corrected bfiles: {COHORT}_harmonized_flipped/{bed,bim,fam}
#   4. Re-runs scoring (step 05) for affected cohorts × traits
#
# USAGE:
#   bash scripts/03b_fix_strand.sh [--force] [--diagnostic PATH]
#     --force       : Re-run even if already done
#     --diagnostic  : Path to diagnostics directory (default: output/diagnostics)
#   (off by default — set FIX_STRAND=yes in config.sh to enable)
#
# INPUTS:
#   ${OUT_ROOT}/geno/<COHORT>_harmonized_shared.{bed,bim,fam} — harmonized bfiles
#   ${DIAG_DIR}/<COHORT>_<trait>_strand_flips.txt              — flip lists
#
# OUTPUTS:
#   ${OUT_ROOT}/geno/<COHORT>_harmonized_flipped.{bed,bim,fam} (when triggered)
#   Updated ${OUT_ROOT}/scores/<COHORT>_<trait>.sscore for affected cohorts/traits
#
# DEPENDS ON: step 03 (harmonized bfiles). Disabled by default — this data set
# has no non-palindromic complement mismatches, so the step has nothing to do.
# =============================================================================
set -euo pipefail
source "$(dirname "$0")/../config.sh"
ensure_dirs

FORCE=""
DIAG_DIR="${OUT_ROOT}/diagnostics"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)     FORCE="yes"; shift ;;
        --diagnostic) DIAG_DIR="$2"; shift 2 ;;
        *)            echo "Unknown option: $1"; exit 1 ;;
    esac
done

log_info "=== Step 03b: Fixing Strand/Allele Orientation Issues ==="

DECISION_LOG="${PROJ_ROOT}/decision_log.md"
FLIP_SUMMARY=""

# =============================================================================
# HELPER: flip one cohort's genotypes for specific SNPs
# =============================================================================
flip_cohort_snps() {
    local cohort="$1"
    local flip_snps_file="$2"    # File with list of SNPs to flip
    local input_bfile="$3"
    local output_prefix="$4"

    if [[ ! -f "$flip_snps_file" ]]; then
        log_warn "  Flip list not found: $flip_snps_file — skipping"
        return 1
    fi

    local n_flip=$(wc -l < "$flip_snps_file")
    if [[ "$n_flip" -eq 0 ]]; then
        log_info "  No SNPs to flip for $cohort"
        return 0
    fi

    if [[ -f "${output_prefix}.bed" && -z "$FORCE" ]]; then
        log_info "  SKIP: $cohort already flipped ($n_flip SNPs)"
        return 0
    fi

    log_info "  Flipping $n_flip SNPs for $cohort..."
    LOG="${LOG_DIR}/strandflip_${cohort}.log"
    "$PLINK2" \
        --bfile "$input_bfile" \
        --flip "$flip_snps_file" permissive \
        --make-bed \
        --threads "$PLINK2_THREADS" \
        --out "$output_prefix" \
        2>&1 | tee "$LOG"
    PLINK_EXIT=${PIPESTATUS[0]}
    if [[ $PLINK_EXIT -ne 0 ]] || grep -q "^Error:" "$LOG" 2>/dev/null; then
        log_error "  PLINK2 flip failed for $cohort — aborting"
        return 1
    fi

    log_info "  -> Flipped genotype written: ${output_prefix}.bed"
}

# =============================================================================
# 1. DETERMINE WHICH COHORTS × TRAITS NEED FLIPPING
# =============================================================================

# The flip list can come from:
#   (a) Diagnostic output (an off-DAG diagnostic that writes per_snp_contribution.tsv)
#   (b) Pre-computed SNP lists
#   (c) Generated by comparing cohort bim files to weight file alleles

STRAND_FLIP_DIR="${OUT_ROOT}/strand_fixes"
mkdir -p "$STRAND_FLIP_DIR"

log_info ""
log_info "--- Determining strand issues ---"

# Check if diagnostic output exists
PER_SNP_CONTRIB="${DIAG_DIR}/per_snp_contribution.tsv"
if [[ -f "$PER_SNP_CONTRIB" ]]; then
    log_info "Using diagnostic output: $PER_SNP_CONTRIB"

    # Read diagnostic: find cohorts where A1 predominantly matches REF instead of ALT
    # (relative to the reference cohort, SHIP0)
    while IFS=$'\t' read -r cohort trait n_weights n_in_geno n_alt n_ref n_missing pct_flipped; do
        if [[ "$trait" == "NonCog" && "$cohort" != "SHIP0" ]]; then
            # Compare NonCog alignment to SHIP0's alignment
            # If a cohort has many more SNPs with A1=REF (vs SHIP0), it likely needs flipping
            log_info "  $cohort NonCog: $pct_flipped% of SNPs have A1=REF"
        fi
    done < <(tail -n +2 "$PER_SNP_CONTRIB")
else
    log_warn "Diagnostic file not found: $PER_SNP_CONTRIB"
    log_warn "Using default assumptions: SOEP and TWINLIFE may need NonCog/Cog flipping"
fi

# =============================================================================
# 2. GENERATE FLIP LISTS FOR AFFECTED COHORTS
# =============================================================================

# Strategy: compare each cohort's bim file allele coding to the weight file.
# SNPs where the cohort's bim A1 (effect allele) does NOT match the weight A1
# are candidates for flipping.
#
# More specifically: for each weight SNP, check if bim A1 matches weight A1.
# If not, add to flip list.

generate_flip_list() {
    local cohort="$1"
    local trait="$2"
    local output_file="$3"

    local bfile
    bfile=$(get_harmonized_bfile "$cohort")

    # Get weight file for this cohort × trait
    case "$trait" in
        "NonCog")
            ncog_trait=$(get_noncog_trait_for_cohort "$cohort")
            tag="${TRAIT_SBAYESR_TAG[$ncog_trait]}"
            weight_file="${WEIGHTS_OUT}/${tag}_sbayesR_chrpos.txt"
            ;;
        "Cog")
            weight_file="${WEIGHTS_OUT}/Cog_sbayesR_chrpos.txt"
            ;;
        "EA4")
            ea4_trait=$(get_ea4_trait_for_cohort "$cohort")
            tag="${TRAIT_SBAYESR_TAG[$ea4_trait]}"
            weight_file="${WEIGHTS_OUT}/${tag}_sbayesR_chrpos.txt"
            ;;
        "Height")
            weight_file="${WEIGHTS_OUT}/Height_sbayesR_chrpos.txt"
            ;;
    esac

    if [[ ! -f "$weight_file" ]]; then
        log_warn "  Weight file not found: $weight_file — cannot generate flip list"
        return 1
    fi

    if [[ ! -f "${bfile}.bim" ]]; then
        log_warn "  Bfile not found: ${bfile}.bim — cannot generate flip list"
        return 1
    fi

    # Compare weight A1 with bim A1 for each SNP
    # bim columns: chr, SNP_id, morgan, pos, A1(REF), A2(ALT)
    # weight columns: SNP, A1, BETA
    #
    # For PLINK2 --flip: we flip alleles for SNPs where the A1 in the data
    # is the OPPOSITE of the A1 in the weight file.
    # This means: if bim A1 != weight A1, flip.
    #
    # BUT: we need to be careful. The bim has REF/ALT, not effect allele.
    # The weight A1 is the EFFECT ALLELE.
    # So if bim REF != weight A1, we need to check if bim ALT == weight A1.
    # If bim ALT == weight A1, the genotype is correctly aligned (effect allele is ALT).
    # If bim REF == weight A1, the genotype is correctly aligned (effect allele is REF).
    # If neither matches, we need to investigate further.

    awk -v weight="$weight_file" -v bim="${bfile}.bim" '
    BEGIN {
        # Read weight file: SNP, A1, BETA
        while ((getline line < weight) > 0) {
            n = split(line, parts, "\t")
            if (n >= 2 && parts[1] != "SNP") {
                weight_a1[parts[1]] = parts[2]
                weight_beta[parts[1]] = parts[3]
            }
        }
        close(weight)

        # Read bim file and compare
        while ((getline line < bim) > 0) {
            n = split(line, parts, "\t")
            snp = parts[2]
            bim_a1 = parts[5]  # REF allele
            bim_a2 = parts[6]  # ALT allele

            if (snp in weight_a1) {
                wa1 = weight_a1[snp]
                # Check: is weight A1 the same as bim A1 or bim A2?
                if (wa1 != bim_a1 && wa1 != bim_a2) {
                    # Weight A1 is neither REF nor ALT — strand issue or
                    # different build; not flipped
                } else if (wa1 == bim_a2) {
                    # Effect allele is ALT in bim — genotype is correctly coded
                    # (effect allele = ALT means people with 2 copies of ALT have higher trait)
                } else {
                    # wa1 == bim_a1 — effect allele is REF — correct
                }
            }
        }
        close(bim)
    }' > /dev/null

    # More targeted approach: identify strand-ambiguous SNPs and check alignment
    # Create flip list using awk to compare bim A1 with weight A1
    # SNPs where: bim A1 != weight A1 AND bim A1 is not the COMPLEMENT of weight A1
    # (complement: A<->T, C<->G)
    awk -v weight="$weight_file" '
    BEGIN { OFS="\t" }
    FNR==NR {
        if (NF >= 2 && $1 != "SNP") {
            w_snp[$1] = $1
            w_a1[$1] = toupper($2)
            w_beta[$1] = $3
        }
        next
    }
    {
        snp = $2
        bim_a1 = toupper($5)
        bim_a2 = toupper($6)

        if (!(snp in w_snp)) next

        wa1 = w_a1[snp]

        # Check if alleles match
        match_a1 = (bim_a1 == wa1)
        match_a2 = (bim_a2 == wa1)

        # For strand: A<->T, C<->G
        # Complement of bim_a1
        comp_bim_a1 = bim_a1
        if (bim_a1 == "A") comp_bim_a1 = "T"
        else if (bim_a1 == "T") comp_bim_a1 = "A"
        else if (bim_a1 == "C") comp_bim_a1 = "G"
        else if (bim_a1 == "G") comp_bim_a1 = "C"

        comp_bim_a2 = bim_a2
        if (bim_a2 == "A") comp_bim_a2 = "T"
        else if (bim_a2 == "T") comp_bim_a2 = "A"
        else if (bim_a2 == "C") comp_bim_a2 = "G"
        else if (bim_a2 == "G") comp_bim_a2 = "C"

        match_comp_a1 = (comp_bim_a1 == wa1)
        match_comp_a2 = (comp_bim_a2 == wa1)

        # If neither direct nor complement matches, it is strand-ambiguous — skip
        # If complement matches, we need to flip
        if (match_comp_a1 || match_comp_a2) {
            # Flag for flipping (effect allele was coded as complement)
            print snp
        } else if (!match_a1 && !match_a2) {
            # Neither direct nor complement matches (different build or
            # variant) — not flipped
        }
    }
    ' "$weight_file" "${bfile}.bim" > "$output_file"

    local n=$(wc -l < "$output_file")
    log_info "  $cohort $trait: generated flip list with $n SNPs"
}

# =============================================================================
# 3. APPLY FLIPS TO AFFECTED COHORTS
# =============================================================================

log_info ""
log_info "--- Applying strand corrections ---"

# Strand issues are platform-level — one flip per cohort applies to ALL traits.
#
# Strategy: generate flip lists from both EA4 and NonCog weights (which cover
# different SNP sets), then apply the union, so SNPs carried only by the NonCog
# weight file are corrected too.
for cohort in SOEP TWINLIFE; do

    # --- Step A: EA4-based flip list ---
    ea4_flip="${STRAND_FLIP_DIR}/${cohort}_EA4_flip_snps.txt"
    if [[ ! -f "$ea4_flip" || -n "$FORCE" ]]; then
        generate_flip_list "$cohort" "EA4" "$ea4_flip" || true
    fi

    # --- Step B: NonCog-specific flip list ---
    noncog_flip="${STRAND_FLIP_DIR}/${cohort}_NonCog_flip_snps.txt"
    if [[ ! -f "$noncog_flip" || -n "$FORCE" ]]; then
        generate_flip_list "$cohort" "NonCog" "$noncog_flip" || true
    fi

    # --- Step C: Union of EA4 and NonCog flip lists (deduplicated) ---
    combined_flip="${STRAND_FLIP_DIR}/${cohort}_combined_flip_snps.txt"
    cat "${ea4_flip:-/dev/null}" "${noncog_flip:-/dev/null}" 2>/dev/null \
        | sort -u \
        > "$combined_flip"
    n_combined=$(wc -l < "$combined_flip")
    log_info "  $cohort combined flip list (EA4 + NonCog): $n_combined SNPs"

    if [[ "$n_combined" -eq 0 ]]; then
        log_info "  No SNPs to flip for $cohort — skipping"
        continue
    fi

    # --- Step D: Apply combined flip to bfile ---
    input_bfile=$(get_harmonized_bfile "$cohort")
    output_prefix="${input_bfile}_flipped"
    flip_cohort_snps "$cohort" "$combined_flip" "$input_bfile" "$output_prefix" || {
        log_error "  Flip failed for $cohort — keeping original genotypes"
        rm -f "${output_prefix}.bed" "${output_prefix}.bim" "${output_prefix}.fam"
        continue
    }

    # Replace the shared files with the flipped version (applies to ALL traits)
    cp "${output_prefix}.bed" "${input_bfile}.bed"
    cp "${output_prefix}.bim" "${input_bfile}.bim"
    cp "${output_prefix}.fam" "${input_bfile}.fam"

    FLIP_SUMMARY="${FLIP_SUMMARY}\n- $cohort: flipped $n_combined SNPs (EA4+NonCog union, applies to all traits)"
done

# =============================================================================
# 4. LOG DECISIONS
# =============================================================================
{
    echo ""
    echo "## Step 03b: Strand/Allele Orientation Fix ($(date '+%Y-%m-%d %H:%M'))"
    echo ""
    echo "- Detected strand issues by comparing bim A1 to weight A1 (EA4 and NonCog)"
    echo "- Flip list = union of EA4-based and NonCog-based flip SNPs (deduplicated)"
    echo "- Strand-ambiguous SNPs (A/T, C/G) were excluded from flipping"
    echo "- Flipped bfiles replace {COHORT}_harmonized_shared.bed/bim/fam in-place"
    echo ""
    echo "### Flip summary"
    echo -e "$FLIP_SUMMARY"
    echo ""
} >> "$DECISION_LOG"

log_info ""
log_info "=== Step 03b complete ==="
log_info ""
log_info "NOTE: After running this script, re-score NonCog for affected cohorts:"
log_info "  bash scripts/05_score_pgi.sh --cohort SOEP --trait NonCog"
log_info "  bash scripts/05_score_pgi.sh --cohort TWINLIFE --trait NonCog"
log_info "Then re-assemble: bash run_pipeline.sh --step 07"
log_info ""
