#!/usr/bin/env bash
# =============================================================================
# _bootstrap_user_config.sh — load (or interactively create) user_config.sh
# =============================================================================
# Sourced by every transfer_*.sh and setup_*.sh script that needs per-user
# settings (cluster username, project root, bin/LD-ref paths, analysis-project
# path on the Mac).
#
# Behaviour:
#   - If user_config.sh exists next to this file, source it and return.
#   - Else, if /dev/tty is usable, walk the user through an interactive setup
#     and write user_config.sh (chmod 600).
#   - Else, print a "copy the example" error and fail.
#
# Usage from a script in the Harmonized/ root:
#   source "$(dirname "${BASH_SOURCE[0]}")/_bootstrap_user_config.sh"
#
# Usage from a script in Harmonized/scripts/:
#   source "$(dirname "${BASH_SOURCE[0]}")/../_bootstrap_user_config.sh"
# =============================================================================

_BOOTSTRAP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_USER_CONFIG="${_BOOTSTRAP_DIR}/user_config.sh"

if [[ -f "$_USER_CONFIG" ]]; then
    # shellcheck source=/dev/null
    source "$_USER_CONFIG"
    unset _BOOTSTRAP_DIR _USER_CONFIG
    return 0 2>/dev/null || exit 0
fi

# user_config.sh missing. Try /dev/tty for interactive setup; refuse otherwise.
if [[ ! -r /dev/tty ]] || [[ ! -w /dev/tty ]]; then
    {
        echo "ERROR: ${_USER_CONFIG} is missing and no TTY is available."
        echo
        echo "Create it before re-running this script, either by writing"
        echo "${_USER_CONFIG} by hand (it sets TARDIS_USER, TARDIS_HOST,"
        echo "TARDIS_PROJECT_ROOT, TARDIS_BIN_DIR, TARDIS_LD_REF_DIR and"
        echo "ANALYSIS_ROOT)"
        echo
        echo "...or by running any transfer_*.sh script in an interactive shell"
        echo "to be walked through the setup."
    } >&2
    return 1 2>/dev/null || exit 1
fi

{
    echo "============================================================"
    echo "First-time setup: writing ${_USER_CONFIG}"
    echo "============================================================"
    echo "This pipeline needs to know your cluster username, project root,"
    echo "where the shared binaries / LD reference live on the cluster, and"
    echo "where the downstream analysis project lives on this machine."
    echo
    echo "Re-run any time by deleting ${_USER_CONFIG}."
    echo
} >/dev/tty

_read_with_default() {
    # $1 = prompt, $2 = default value (may be empty). Reads from /dev/tty.
    local prompt="$1"
    local default="$2"
    local result
    if [[ -n "$default" ]]; then
        read -r -p "${prompt} [${default}]: " result </dev/tty
    else
        read -r -p "${prompt}: " result </dev/tty
    fi
    printf '%s' "${result:-$default}"
}

TARDIS_USER=""
while [[ -z "$TARDIS_USER" ]]; do
    TARDIS_USER="$(_read_with_default "Cluster username (login)" "${CLUSTER_USER:-}")"
    [[ -z "$TARDIS_USER" ]] && echo "  Cluster username is required." >/dev/tty
done

TARDIS_HOST="$(_read_with_default "Cluster hostname" "${CLUSTER_HOST:-cluster.example.org}")"
TARDIS_PROJECT_ROOT="$(_read_with_default \
    "Cluster project root" \
    "${CLUSTER_PROJECT_ROOT:-/path/to/cluster_project_root}/80_years_GxE_on_Education_in_Germany/genotype")"
TARDIS_BIN_DIR="$(_read_with_default \
    "Cluster bin dir (gctb, plink, plink2)" \
    "${CLUSTER_BIN_DIR:-/path/to/cluster_bin_dir}/bin")"
TARDIS_LD_REF_DIR="$(_read_with_default \
    "Cluster UKB LD reference dir" \
    "${CLUSTER_BIN_DIR:-/path/to/cluster_bin_dir}/reference/ukb_50k_bigset_2.8M")"
ANALYSIS_ROOT="$(_read_with_default \
    "Local analysis project root (on this machine)" \
    "${HOME}/Documents/80_years_Education_Genomics_in_Germany_harmonized")"

unset -f _read_with_default

{
    echo
    echo "Note: this pipeline assumes SSH key-based auth to the cluster. Verify with:"
    echo "  ssh ${TARDIS_USER}@${TARDIS_HOST} echo ok"
    echo "If that still prompts for a password, run \`ssh-copy-id ${TARDIS_USER}@${TARDIS_HOST}\` first."
    echo
} >/dev/tty

cat > "$_USER_CONFIG" <<EOF
# user_config.sh — per-user settings for the Harmonized PGI pipeline.
# Generated by _bootstrap_user_config.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ').
# Delete this file and re-run any transfer_*.sh script to regenerate.
# This file is gitignored.

export TARDIS_USER="${TARDIS_USER}"
export TARDIS_HOST="${TARDIS_HOST}"
export TARDIS_SSH="\${TARDIS_USER}@\${TARDIS_HOST}"
export TARDIS_PROJECT_ROOT="${TARDIS_PROJECT_ROOT}"
export TARDIS_BIN_DIR="${TARDIS_BIN_DIR}"
export TARDIS_LD_REF_DIR="${TARDIS_LD_REF_DIR}"
export ANALYSIS_ROOT="${ANALYSIS_ROOT}"
EOF
chmod 600 "$_USER_CONFIG"

echo "Wrote ${_USER_CONFIG} (mode 600)." >/dev/tty
echo >/dev/tty

# shellcheck source=/dev/null
source "$_USER_CONFIG"
unset _BOOTSTRAP_DIR _USER_CONFIG
return 0 2>/dev/null || exit 0
