#!/usr/bin/env bash
# =============================================================================
# _bootstrap_user_config.sh — load (or interactively create) user_config.sh
# =============================================================================
# Sourced by every transfer_*.sh script that needs per-user settings
# (Tardis username, project roots, bin path, local DATA_ROOT).
#
# Behaviour:
#   - If user_config.sh exists next to this file, source it and return.
#   - Else, if /dev/tty is usable, walk the user through an interactive setup
#     and write user_config.sh (chmod 600).
#   - Else, print a "copy the example" error and fail.
#
# Usage from a script at the section root:
#   source "$(dirname "${BASH_SOURCE[0]}")/_bootstrap_user_config.sh"
# =============================================================================

_BOOTSTRAP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_USER_CONFIG="${_BOOTSTRAP_DIR}/user_config.sh"
_USER_CONFIG_EXAMPLE="${_BOOTSTRAP_DIR}/user_config.sh.example"

if [[ -f "$_USER_CONFIG" ]]; then
    # shellcheck source=/dev/null
    source "$_USER_CONFIG"
    unset _BOOTSTRAP_DIR _USER_CONFIG _USER_CONFIG_EXAMPLE
    return 0 2>/dev/null || exit 0
fi

# user_config.sh missing. Try /dev/tty for interactive setup; refuse otherwise.
if [[ ! -r /dev/tty ]] || [[ ! -w /dev/tty ]]; then
    {
        echo "ERROR: ${_USER_CONFIG} is missing and no TTY is available."
        echo
        echo "Create it before re-running this script, either by copying the"
        echo "template:"
        echo "  cp ${_USER_CONFIG_EXAMPLE} ${_USER_CONFIG}"
        echo "  \$EDITOR ${_USER_CONFIG}"
        echo
        echo "...or by running any transfer_*.sh script in an interactive shell"
        echo "to be walked through the setup."
    } >&2
    return 1 2>/dev/null || exit 1
fi

{
    echo "============================================================"
    echo "First-time setup: writing ${_USER_CONFIG}"
    echo "============================================================"
    echo "This pipeline needs to know your Tardis username, where THIS"
    echo "section lives on Tardis, where the upstream GENOTYPE section"
    echo "lives on Tardis (we reuse its harmonized bfiles), the shared"
    echo "bin directory, and your local DATA_ROOT."
    echo
    echo "Re-run any time by deleting ${_USER_CONFIG}."
    echo
} >/dev/tty

_read_with_default() {
    local prompt="$1"
    local default="$2"
    local result
    if [[ -n "$default" ]]; then
        read -r -p "${prompt} [${default}]: " result </dev/tty
    else
        read -r -p "${prompt}: " result </dev/tty
    fi
    printf '%s' "${result:-$default}"
}

TARDIS_USER=""
while [[ -z "$TARDIS_USER" ]]; do
    TARDIS_USER="$(_read_with_default "Tardis username (cluster login)" "")"
    [[ -z "$TARDIS_USER" ]] && echo "  Tardis username is required." >/dev/tty
done

TARDIS_HOST="$(_read_with_default "Tardis hostname" "your.cluster.hostname")"
TARDIS_PROJECT_ROOT="$(_read_with_default \
    "Tardis project root for THIS section (h2_snp)" \
    "/path/to/cluster_project_root/h2_snp")"
TARDIS_GENOTYPE_PROJECT_ROOT="$(_read_with_default \
    "Tardis project root for the upstream GENOTYPE pipeline" \
    "/path/to/cluster_project_root/genotype")"
TARDIS_BIN_DIR="$(_read_with_default \
    "Tardis bin dir (gcta64, plink, plink2)" \
    "/path/to/cluster_bin_dir")"
DATA_ROOT="$(_read_with_default \
    "Local DATA_ROOT (the shared volume mirror)" \
    "/path/to/data_root")"

unset -f _read_with_default

{
    echo
    echo "Note: this pipeline assumes SSH key-based auth to Tardis. Verify with:"
    echo "  ssh ${TARDIS_USER}@${TARDIS_HOST} echo ok"
    echo "If that still prompts for a password, run \`ssh-copy-id ${TARDIS_USER}@${TARDIS_HOST}\` first."
    echo
} >/dev/tty

cat > "$_USER_CONFIG" <<EOF
# user_config.sh — per-user settings for the SNP-heritability pipeline.
# Generated by _bootstrap_user_config.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ').
# Delete this file and re-run any transfer_*.sh script to regenerate.
# This file is gitignored.

export TARDIS_USER="${TARDIS_USER}"
export TARDIS_HOST="${TARDIS_HOST}"
export TARDIS_SSH="\${TARDIS_USER}@\${TARDIS_HOST}"
export TARDIS_PROJECT_ROOT="${TARDIS_PROJECT_ROOT}"
export TARDIS_GENOTYPE_PROJECT_ROOT="${TARDIS_GENOTYPE_PROJECT_ROOT}"
export TARDIS_BIN_DIR="${TARDIS_BIN_DIR}"
export DATA_ROOT="${DATA_ROOT}"
EOF
chmod 600 "$_USER_CONFIG"

echo "Wrote ${_USER_CONFIG} (mode 600)." >/dev/tty
echo >/dev/tty

# shellcheck source=/dev/null
source "$_USER_CONFIG"
unset _BOOTSTRAP_DIR _USER_CONFIG _USER_CONFIG_EXAMPLE
return 0 2>/dev/null || exit 0
